version: '3.7'

services:
  omicsfe:
    container_name: omicsfe
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${REACT_APP_PORT}:3000
    command: npm start
    environment:
      - REACT_APP_BACKEND_ENDPOINT=http://y.xyz.com
    env_file:
      - .env
    networks:
      - viascientific
networks:
  viascientific:
    name: viascientific
